<?php
return [
    'GET' => [
        'area' => ['controller' => 'AreaController', 'action' => 'QueryAllController', 'require_session' => true],
        'area/(.+)' => ['controller' => 'AreaController', 'action' => 'QueryOneController', 'require_session' => true],
        'areaAct/(.+)' => ['controller' => 'AreaController', 'action' => 'ActivateController', 'require_session' => true],
        'areaAct' => ['controller' => 'AreaController', 'action' => 'QueryActController', 'require_session' => true],
        'puntoAct/(.+)' => ['controller' => 'PuntoController', 'action' => 'ActivateController', 'require_session' => true],
        'usuario' => ['controller' => 'UsuarioController', 'action' => 'QueryAllController', 'require_session' => true],
        'usuario/(.+)' => ['controller' => 'UsuarioController', 'action' => 'QueryOneController', 'require_session' => true],
        'punto' => ['controller' => 'PuntoController', 'action' => 'QueryAllController'],
        'punto/(.+)' => ['controller' => 'PuntoController', 'action' => 'QueryOneController', 'require_session' => true],
        'contenidoDinamicoAct/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'ActivateController', 'require_session' => true],
        'areapunto_punto/(.+)' => ['controller' => 'PuntosAreasController', 'action' => 'QueryAreaPunto_PuntoController', 'require_session' => true],
        'puntosareas/allpuntosaccesoarea/(.+)' => ['controller' => 'PuntosAreasController', 'action' => 'QueryAllPuntosAccesoAreaController', 'require_session' => true],
        'userAcces/(.+)' => ['controller' => 'UsuarioController', 'action' => 'QueryAllUsuariosAccesoAreaController', 'require_session' => true],
        // 'contenido' => ['controller' => 'ContenidoController', 'action' => 'QueryAllController'],
        // 'contenido/(\d+)' => ['controller' => 'ContenidoController', 'action' => 'QueryOneController', 'require_session' => true],
        'trimestre' => ['controller' => 'TrimestreController', 'action' => 'QueryAllController', 'require_session' => true],
        'trimestre/(.+)' => ['controller' => 'TrimestreController', 'action' => 'QueryOneController', 'require_session' => true],
        'activarUser/(.+)' => ['controller' => 'UsuarioController', 'action' => 'ActivateController', 'require_session' => true],
        'ejercicio' => ['controller' => 'EjercicioController', 'action' => 'QueryAllController', 'require_session' => true],
        'ejercicio/(.+)' => ['controller' => 'EjercicioController', 'action' => 'QueryOneController', 'require_session' => true],
        'ejercicioAct/(.+)' => ['controller' => 'EjercicioController', 'action' => 'ActivateController', 'require_session' => true],
        'trimestreAct/(.+)' => ['controller' => 'TrimestreController', 'action' => 'ActivateController' ,'require_session' => true],
        'titulosAct/(.+)' => ['controller' => 'TitulosController', 'action' => 'ActivateController', 'require_session' => true],
        'puntoUser/(.+)' => ['controller' => 'PuntoController', 'action' => 'QueryPuntoUserController', 'require_session' => true],
        'titulo/(.+)' => ['controller' => 'TitulosController', 'action' => 'QueryOneController', 'require_session' => true],
        'titulosCompletos/(.+)' => ['controller' => 'TitulosController', 'action' => 'mostrarTitulosSubtitulos'],
        'tituloPadre/(.+)' => ['controller' => 'TitulosController', 'action' => 'QueryTituloPadre', 'require_session' => true],
        'titulosdepunto/(.+)' => ['controller' => 'TitulosController', 'action' => 'QueryTitulosPuntoController', 'require_session' => true],
        'titulosmaspunto/(.+)' => ['controller' => 'TitulosController', 'action' => 'QueryTitulosMasPuntoController', 'require_session' => true],
        'subtitulosPorTema/(.+)' => ['controller' => 'TitulosController', 'action' => 'mostrarSubtitulosByTitulo', 'require_session' => true],
        'subtituloData/(.+)' => ['controller' => 'TitulosController', 'action' => 'QueryOneControllerSubtema', 'require_session' => true],
        'contenidoDinamico/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'QueryAllController', 'require_session' => true],
        'onecontenidoDinamico/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'QueryOneController', 'require_session' => true],
        'contenidoEstatico/(.+)' => ['controller' => 'ContenidoEstaticoController', 'action' => 'QueryAllController'],
        'contenidoEstaticoAct/(.+)' => ['controller' => 'ContenidoEstaticoController', 'action' => 'ActivateController', 'require_session' => true],
        'oneContenidoEstatico/(.+)' => ['controller' => 'ContenidoEstaticoController', 'action' => 'QueryOneController'],
        'getDocument/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'getDocument'],
        // El de historial se deja sin sesión dado que carga cada que entra
        'historial' => ['controller' => 'HistorialController', 'action' => 'QueryAllVistosController'],
        'historialNoVisto' => ['controller' => 'HistorialController', 'action' => 'QueryAllNoVistosController', 'require_session' => true],
        'verHistorial/(.+)' => ['controller' => 'HistorialController', 'action' => 'verController', 'require_session' => true],
        'historialAct/(.+)' => ['controller' => 'HistorialController', 'action' => 'ActivateController', 'require_session' => true],
    ],
    'POST' => [
        'area' => ['controller' => 'AreaController', 'action' => 'InsertController',  'require_session' => true],
        'usuario' => ['controller' => 'UsuarioController', 'action' => 'InsertController',  'require_session' => true],
        'punto' => ['controller' => 'PuntoController', 'action' => 'InsertController',  'require_session' => true],
        'trimestre' => ['controller' => 'TrimestreController', 'action' => 'InsertController',  'require_session' => true],
        'verificarUser' => ['controller' => 'UsuarioController', 'action' => 'VerificarUserController'],
        'puntosareas/insertoractivate_puntoArea' => ['controller' => 'PuntosAreasController', 'action' => 'InsertOrActivate_PuntoAreaController',  'require_session' => true],
        'puntosareas/desactivate_puntoarea' => ['controller' => 'PuntosAreasController', 'action' => 'Desactivate_PuntoAreaController',  'require_session' => true],
        'ejercicio' => ['controller' => 'EjercicioController', 'action' => 'InsertController',  'require_session' => true],
        'titulos' => ['controller' => 'TitulosController', 'action' => 'InsertController',  'require_session' => true],
        'subtitulo' => ['controller' => 'TitulosController', 'action' => 'InsertSubtemaController',  'require_session' => true],
        'contenidoDinamico' => ['controller' => 'ContenidoDinamicoController', 'action' => 'InsertDocumentoController'],
        'UpdatecontentDinamico/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'UpdateDocumentoController',  'require_session' => true],
        'contenidoEstatico' => ['controller' => 'ContenidoEstaticoController', 'action' => 'InsertContenidoEstaticoController',  'require_session' => true],
        'orderPuntos' => ['controller' => 'PuntoController', 'action' => 'UpdateOrderPuntos',  'require_session' => true],
        'buscarPDF' => ['controller' => 'ContenidoDinamicoController', 'action' => 'SearchFile'],
        'VerifySesion' => ['controller' => 'UsuarioController', 'action' => 'VerifySesion',  'require_session' => true],
    ],
    'PUT' => [
        'area/(.+)' => ['controller' => 'AreaController', 'action' => 'UpdateController', 'require_session' => true],
        'usuario/(.+)' => ['controller' => 'UsuarioController', 'action' => 'UpdateController', 'require_session' => true],
        'punto/(.+)' => ['controller' => 'PuntoController', 'action' => 'UpdateController', 'require_session' => true],
        'trimestre/(.+)' => ['controller' => 'TrimestreController', 'action' => 'UpdateController', 'require_session' => true],
        'ejercicio/(.+)' => ['controller' => 'EjercicioController', 'action' => 'UpdateController', 'require_session' => true],
        'titulos/(.+)' => ['controller' => 'TitulosController', 'action' => 'UpdateController', 'require_session' => true],
        'subtitulo/(.+)' => ['controller' => 'TitulosController', 'action' => 'UpdateControllerSubtema', 'require_session' => true],
        'UpdatecontentEstatico/(.+)' => ['controller' => 'ContenidoEstaticoController', 'action' => 'UpdateController', 'require_session' => true],
    ],
    'DELETE' => [
        'area/(.+)' => ['controller' => 'AreaController', 'action' => 'DeleteController', 'require_session' => true],
        'usuario/(.+)' => ['controller' => 'UsuarioController', 'action' => 'DeleteController', 'require_session' => true],
        'punto/(.+)' => ['controller' => 'PuntoController', 'action' => 'DeleteController', 'require_session' => true],
        'trimestre/(.+)' => ['controller' => 'TrimestreController', 'action' => 'DeleteController', 'require_session' => true],
        'ejercicio/(.+)' => ['controller' => 'EjercicioController', 'action' => 'DeleteController', 'require_session' => true],
        'titulos/(.+)' => ['controller' => 'TitulosController', 'action' => 'DeleteController', 'require_session' => true],
        'contenidoDinamico/(.+)' => ['controller' => 'ContenidoDinamicoController', 'action' => 'DeleteController', 'require_session' => true],
        'contenidoEstatico/(.+)' => ['controller' => 'ContenidoEstaticoController', 'action' => 'DeleteController', 'require_session' => true],
        'historial/(.+)' => ['controller' => 'HistorialController', 'action' => 'DeleteController', 'require_session' => true],
    ],
];
